#!/bin/bash
#$ -S /bin/bash
#$ -cwd                   # Run job from directory where submitted
#$ -o outputfile.log
#$ -m ea
#$ -N rnn_nmt
#$ -M henry.maguire@postgrad.manchester.ac.uk
#$ -j y
#$ -V                     # Inherit environment (modulefile) settings
#$ -pe smp.pe 24 -l haswell          # Number of cores on a single compute node. Can be 2-22.
module load apps/gcc/tensorflow/1.0.0-py27-cpu
python machine-translator.py
